### ISSUE TITLE
Tests should include assertions

### ISSUE THREAD

**Issue by CandyKIng1991** [fuzhengwei/small-spring#15]
sonar检测抛出的问题,在idea里加了这个插件就会报这个错.不是标准的test.下载的本地已经改正

Noncompliant Code Example
@Test
public void testDoSomething() {  // Noncompliant
  MyClass myClass = new MyClass();
  myClass.doSomething();
}
Compliant Solution
Example when com.company.CompareToTester#compare* is used as parameter to the rule.

import com.company.CompareToTester;

@Test
public void testDoSomething() {
  MyClass myClass = new MyClass();
  assertNull(myClass.doSomething());  // JUnit assertion
  assertThat(myClass.doSomething()).isNull();  // Fest assertion
}

@Test
public void testDoSomethingElse() {
  MyClass myClass = new MyClass();
  new CompareToTester().compareWith(myClass);  // Compliant - custom assertion method defined as rule parameter
  CompareToTester.compareStatic(myClass);  // Compliant
}

**Comment by fuzhengwei** [comment]
如：[https://github.com/fuzhengwei/small-spring/issues/17](https://github.com/fuzhengwei/small-spring/issues/17)
