### ISSUE TITLE
small-spring-step-02的test改为如下是不是好一些.

### ISSUE THREAD

**Issue by CandyKIng1991** [fuzhengwei/small-spring#18]
// 1.初始化 BeanFactory
        DefaultListableBeanFactory beanFactory = new DefaultListableBeanFactory();

        // 2.注册 bean
        BeanDefinition beanDefinition = new BeanDefinition(UserService.class);
        beanFactory.registerBeanDefinition("userService", beanDefinition);

        // 3.第一次获取 bean
        UserService userService = (UserService) beanFactory.getBean("userService");
       userService.queryUserInfo(1);

        // 4.第二次获取 bean from Singleton
        UserService userService_singleton = (UserService) beanFactory.getBean("userService");
        userService_singleton.queryUserInfo(2);

        assertNotNull(userService_singleton);

打印:
      查询用户信息: 第1次
      查询用户信息: 第2次

**Comment by fuzhengwei** [comment]
嗯，可以适当去调整验证，这样学到的也多。
