### ISSUE TITLE
有个小问题，希望小傅哥能解惑

### ISSUE THREAD

**Issue by Stan982314760** [fuzhengwei/small-spring#2]
AbstractBeanFactory#addBeanPostProcessor(BeanPostProcessor beanPostProcessor) 这个方法，
如果BeanPostProcessor没有重写equals方法，为什么要先删一次，再添加呢？

**Comment by fuzhengwei** [comment]
1. ArrayList 的添加是不防重的，允许相同元素存在
   
   ```java
	public boolean add(E e) {
       ensureCapacityInternal(size + 1);
       elementData[size++] = e;
       return true;
   }
   ```
   
2. 删除元素的时候，使用 equals 进行比对，所以可以避免同一个对象的存在2次
   
   ```java
   for (int index = 0; index < size; index++)
    if (o.equals(elementData[index])) {
        fastRemove(index);
        return true;
    }
   ```
   
3. 删除再添加可以起到排序的效果，`BeanPostProcessor` 可能本来在前面，那么移除再添加后，则变到最后面。这样就可以保证与用户编写的顺序保持一致，尽可能让用户的配置顺序就是执行顺序。
