### ISSUE TITLE
避免空指针异常

### ISSUE THREAD

**Issue by Nwxshm** [fuzhengwei/small-spring#21]
AbstractAutowireCapableBeanFactory类中的createBean方法中在属性赋值时应该增加一个为空判断,不为空才继续赋值，不然，无属性值的对象进入 applyPropertyValues方法会导致空指针异常。
@Override
    protected Object createBean(String beanName, BeanDefinition beanDefinition, Object[] args) throws BeansException {
        Object bean = null;
        try {
            bean = createBeanInstance(beanName, beanDefinition, args);
            if (Objects.nonNull(beanDefinition.getPropertyValues())){
                applyPropertyValues(beanName, bean, beanDefinition);
            }
        }catch (Exception e){
            throw new BeansException("failed to create this object...");
        }
        addSingleton(beanName, bean);
        return bean;
    }

**Comment by Nwxshm** [comment]
内容为第5章  属性注入和依赖对象

**Comment by fuzhengwei** [comment]
赞，可以提交一个PR
