### ISSUE TITLE
关于BeanPostProcessor的问题

### ISSUE THREAD

**Issue by TequilaCN** [fuzhengwei/small-spring#25]
您好, 在执行bean后置处理器的时候这段代码好像有点问题
cn.bugstack.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory#initializeBean
![image](https://user-images.githubusercontent.com/12484791/132126220-60771117-b64d-4e0c-a6fb-c61eb13be002.png)
这里应该是传wrappedBean吧? 不然可能会造成applyBeanPostProcessorsBeforeInitialization所做的修改丢失。

**Comment by TequilaCN** [comment]
从06开始

**Comment by xiaoguyu** [comment]
按我的理解，确实是传错参数了。可以直接去看看spring源码AbstractAutowireCapableBeanFactory#initializeBean方法

**Comment by fuzhengwei** [comment]
收到，修复完毕06-17
