### ISSUE TITLE
第三章里如果存在参数个数一样但是类型不一样的构造方法要如何判断区别呢

### ISSUE THREAD

**Issue by mi-im** [fuzhengwei/small-spring#58]
AbstractAutowireCapableBeanFactory 中的createBeanInstance方法
`protected Object createBeanInstance(BeanDefinition beanDefinition, String beanName, Object[] args) {
        Constructor constructorToUse = null;
        Class<?> beanClass = beanDefinition.getBeanClass();
        Constructor<?>[] declaredConstructors = beanClass.getDeclaredConstructors();
        for (Constructor ctor : declaredConstructors) {
            if (null != args && ctor.getParameterTypes().length == args.length) {
                constructorToUse = ctor;
                break;
            }
        }
        return getInstantiationStrategy().instantiate(beanDefinition, beanName, constructorToUse, args);
    }`

**Comment by Whale-lyi** [comment]
添加一个循环，使用 `isAssignableFrom()` 来判断调用参数类型是否满足方法声明中的参数类型
```java
for (Constructor<?> ctor: declaredConstructors) {
    Class<?>[] parameterTypes = ctor.getParameterTypes();
    if (parameterTypes.length == args.length) {
        boolean isMatch = true;
        for (int i = 0; i < args.length; i++) {
            if (args[i] != null && !parameterTypes[i].isAssignableFrom(args[i].getClass())) {
                isMatch = false;
                break;
            }
        }
        if (isMatch) {
            constructorToUse = ctor;
            break;
        }
    }
}
```

**Comment by Whale-lyi** [comment]
添加一个循环，使用 `isAssignableFrom()` 来判断调用参数类型是否满足方法声明中的参数类型
```java
for (Constructor<?> ctor: declaredConstructors) {
    Class<?>[] parameterTypes = ctor.getParameterTypes();
    if (parameterTypes.length == args.length) {
        boolean isMatch = true;
        for (int i = 0; i < args.length; i++) {
            if (args[i] != null && !parameterTypes[i].isAssignableFrom(args[i].getClass())) {
                isMatch = false;
                break;
            }
        }
        if (isMatch) {
            constructorToUse = ctor;
            break;
        }
    }
}
```

**Comment by mi-im** [comment]
> ```java
> isAssignableFrom
> ```

谢谢 之前到处找就是没找到这个类似的方法
